services:
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - '443:443'

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro   # Configuration Caddy
      - caddy_data:/data                     # Certificats et données Caddy
      - caddy_config:/config                 # Configuration interne de Caddy
    networks:
      - phardev


  django:
    image: ghcr.io/mysteriousbaboon/phardev:latest
    container_name: django
    ports:
      - "8000:8000"
    networks:
      - phardev

volumes:
  caddy_data:
  caddy_config:

networks:
  phardev:
    driver: bridge
#certbot:
#    image: certbot/certbot
#    volumes:
#      - ./letsencrypt:/etc/letsencrypt
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#    entrypoint: >
#      sh -c "certbot certonly --standalone
#      --agree-tos
#      --email your-email@example.com
#      -d yourdomain.com"
