# Generated by Django 5.1.3 on 2025-01-04 14:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalProduct',
            fields=[
                ('code_13_ref', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(verbose_name='Produit')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Date')),
                ('universe', models.CharField(max_length=255, verbose_name='Univers')),
                ('category', models.CharField(max_length=255, verbose_name='Catégorie')),
                ('sub_category', models.CharField(max_length=255, verbose_name='Sous catégorie')),
                ('brand_lab', models.CharField(blank=True, max_length=255, null=True, verbose_name='Marque - Labo')),
                ('lab_distributor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Laboratoire - Distributeur')),
                ('range_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Gamme')),
                ('specificity', models.CharField(blank=True, max_length=255, null=True, verbose_name='Spécificité')),
                ('family', models.CharField(blank=True, max_length=255, null=True, verbose_name='Famille')),
                ('sub_family', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sous famille')),
                ('tva_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% TVA')),
                ('free_access', models.BooleanField(blank=True, null=True, verbose_name='Libre accès')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_nat', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('ca', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name="Chiffre d'affaires")),
                ('area', models.CharField(blank=True, max_length=255, null=True, verbose_name='Zone géographique')),
                ('employees_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Nombre d'employés")),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresse')),
            ],
        ),
        migrations.CreateModel(
            name='InternalProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('internal_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('TVA', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='TVA')),
                ('code_13_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.globalproduct')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.pharmacy')),
            ],
        ),
        migrations.CreateModel(
            name='InventorySnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('stock', models.SmallIntegerField(default=0, verbose_name='Stock')),
                ('price_with_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weighted_average_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_history', to='data.internalproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_id', models.PositiveBigIntegerField()),
                ('step', models.PositiveSmallIntegerField()),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='data.pharmacy')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qte', models.PositiveSmallIntegerField(verbose_name='Quantité')),
                ('qte_r', models.PositiveSmallIntegerField(verbose_name='Quantité Réceptionnée')),
                ('qte_a', models.SmallIntegerField(verbose_name='Quantité Attendue')),
                ('qte_ug', models.PositiveSmallIntegerField(verbose_name='Quantité Unité Gratuite')),
                ('qte_ec', models.SmallIntegerField(verbose_name='Quantité en Écart')),
                ('qte_ar', models.SmallIntegerField(verbose_name='Quantité à Réceptionner')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_orders', to='data.order', verbose_name='Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_orders', to='data.internalproduct', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Order',
                'verbose_name_plural': 'Product Orders',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.SmallIntegerField()),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_history', to='data.inventorysnapshot', verbose_name='Inventory Snapshot')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_supplier', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.pharmacy')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='data.supplier'),
        ),
        migrations.AddIndex(
            model_name='inventorysnapshot',
            index=models.Index(fields=['product', 'date'], name='data_invent_product_05d8e4_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorysnapshot',
            index=models.Index(fields=['date'], name='data_invent_date_215c7c_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorysnapshot',
            index=models.Index(fields=['product'], name='data_invent_product_a1213c_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorysnapshot',
            constraint=models.UniqueConstraint(fields=('product', 'date'), name='unique_snapshot_constraint'),
        ),
        migrations.AddConstraint(
            model_name='internalproduct',
            constraint=models.UniqueConstraint(fields=('pharmacy', 'internal_id'), name='unique_product_constraint'),
        ),
        migrations.AddConstraint(
            model_name='productorder',
            constraint=models.UniqueConstraint(fields=('order', 'product'), name='unique_productorder_constraint'),
        ),
        migrations.AddConstraint(
            model_name='sales',
            constraint=models.UniqueConstraint(fields=('date', 'product'), name='unique_dateproductsale_constraint'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('pharmacy', 'code_supplier'), name='unique_supplier_constraint'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('internal_id', 'pharmacy'), name='unique_order_constraint'),
        ),
    ]
