# Generated by Django 5.1.3 on 2024-12-07 18:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalProduct',
            fields=[
                ('code_13_ref', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.TextField(verbose_name='Produit')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Date')),
                ('universe', models.CharField(max_length=255, verbose_name='Univers')),
                ('category', models.CharField(max_length=255, verbose_name='Catégorie')),
                ('sub_category', models.CharField(max_length=255, verbose_name='Sous catégorie')),
                ('brand_lab', models.CharField(max_length=255, verbose_name='Marque - Labo')),
                ('lab_distributor', models.CharField(max_length=255, verbose_name='Laboratoire - Distributeur')),
                ('range_name', models.CharField(max_length=255, verbose_name='Gamme')),
                ('specificity', models.CharField(blank=True, max_length=255, null=True, verbose_name='Spécificité')),
                ('family', models.CharField(max_length=255, verbose_name='Famille')),
                ('sub_family', models.CharField(max_length=255, verbose_name='Sous famille')),
                ('tva_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% TVA')),
                ('free_access', models.BooleanField(verbose_name='Libre accès')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('ca', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name="Chiffre d'affaires")),
                ('area', models.CharField(blank=True, max_length=255, null=True, verbose_name='Zone géographique')),
                ('employees_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Nombre d'employés")),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresse')),
            ],
        ),
        migrations.CreateModel(
            name='InternalProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('internal_id', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('TVA', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('code_13_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.globalproduct')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.pharmacy')),
            ],
        ),
        migrations.CreateModel(
            name='InventorySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('price_with_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weighted_average_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_history', to='data.internalproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_id', models.PositiveBigIntegerField()),
                ('step', models.PositiveSmallIntegerField()),
                ('sent_date', models.DateTimeField()),
                ('delivery_date', models.DateField()),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.pharmacy')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qte', models.IntegerField(verbose_name='Quantité')),
                ('qte_r', models.IntegerField(verbose_name='Quantité Réceptionnée')),
                ('qte_a', models.IntegerField(verbose_name='Quantité Attendue')),
                ('qte_ug', models.IntegerField(verbose_name='Quantité Unité Gratuite')),
                ('qte_ec', models.IntegerField(verbose_name='Quantité en Écart')),
                ('qte_ar', models.IntegerField(verbose_name='Quantité à Réceptionner')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.internalproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('operator_code', models.CharField(max_length=25)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.inventorysnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_supplier', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('code_supplier', 'name'), name='unique_supplier_constraint')],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.supplier'),
        ),
        migrations.AddConstraint(
            model_name='internalproduct',
            constraint=models.UniqueConstraint(fields=('pharmacy', 'internal_id', 'code_13_ref'), name='unique_product_constraint'),
        ),
        migrations.AddConstraint(
            model_name='productorder',
            constraint=models.UniqueConstraint(fields=('order', 'product'), name='unique_productorder_constraint'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('internal_id', 'pharmacy'), name='unique_order_constraint'),
        ),
    ]
