# Generated by Django 5.1.3 on 2024-11-25 11:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_id', models.PositiveBigIntegerField()),
                ('step', models.PositiveSmallIntegerField()),
                ('sent_date', models.DateTimeField()),
                ('delivery_date', models.DateField()),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.pharmacy')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_id', models.PositiveBigIntegerField()),
                ('code_13_ref', models.CharField(blank=True, max_length=13, null=True)),
                ('name', models.CharField(max_length=255)),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('TVA', models.DecimalField(decimal_places=2, max_digits=4)),
                ('price_with_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weighted_average_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.pharmacy')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_id', models.PositiveBigIntegerField()),
                ('qte', models.IntegerField(verbose_name='Quantité')),
                ('qte_r', models.IntegerField(verbose_name='Quantité Réceptionnée')),
                ('qte_a', models.IntegerField(verbose_name='Quantité Attendue')),
                ('qte_ug', models.IntegerField(verbose_name='Quantité Unité de Gestion')),
                ('qte_ec', models.IntegerField(verbose_name='Quantité en Écart')),
                ('qte_ar', models.IntegerField(verbose_name='Quantité à Réceptionner')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.product')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.pharmacy')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.product')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_supplier', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('code_supplier', 'name'), name='unique_supplier_constraint')],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.supplier'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('pharmacy', 'internal_id', 'code_13_ref'), name='unique_product_constraint'),
        ),
        migrations.AddConstraint(
            model_name='productorder',
            constraint=models.UniqueConstraint(fields=('internal_id', 'order', 'product'), name='unique_productorder_constraint'),
        ),
        migrations.AddConstraint(
            model_name='sales',
            constraint=models.UniqueConstraint(fields=('time', 'product', 'pharmacy'), name='unique_sale_constraint'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('internal_id', 'pharmacy'), name='unique_order_constraint'),
        ),
    ]
