# Generated by Django 5.1.3 on 2024-12-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalproduct',
            name='brand_lab',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Marque - Labo'),
        ),
        migrations.AlterField(
            model_name='globalproduct',
            name='family',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Famille'),
        ),
        migrations.AlterField(
            model_name='globalproduct',
            name='lab_distributor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Laboratoire - Distributeur'),
        ),
        migrations.AlterField(
            model_name='globalproduct',
            name='range_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Gamme'),
        ),
        migrations.AlterField(
            model_name='globalproduct',
            name='sub_family',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sous famille'),
        ),
    ]
