# Generated by Django 5.1.3 on 2025-01-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalproduct',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='globalproduct',
            name='sub_category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sous catégorie'),
        ),
    ]
