# Generated by Django 5.1.3 on 2024-12-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_globalproduct_brand_lab_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalproduct',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
