# Generated by Django 5.1.3 on 2025-01-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_globalproduct_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='qte',
            field=models.SmallIntegerField(verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='qte_r',
            field=models.SmallIntegerField(verbose_name='Quantité Réceptionnée'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='qte_ug',
            field=models.SmallIntegerField(verbose_name='Quantité Unité Gratuite'),
        ),
    ]
