# Generated by Django 5.1.3 on 2024-11-25 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_product_tva_alter_product_price_with_tax_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='internal_id',
        ),
    ]
