# Generated by Django 5.1.3 on 2024-12-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_globalproduct_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalproduct',
            name='tva_percentage',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='% TVA'),
        ),
    ]
