# Generated by Django 5.1.3 on 2025-01-14 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_productorder_qte_alter_productorder_qte_r_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalproduct',
            name='TVA',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='TVA'),
        ),
    ]
