# Generated by Django 5.1.3 on 2024-12-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_globalproduct_tva_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalproduct',
            name='tva_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% TVA'),
        ),
    ]
