# Generated by Django 5.1.3 on 2024-12-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_globalproduct_tva_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='id_nat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='globalproduct',
            name='free_access',
            field=models.BooleanField(blank=True, null=True, verbose_name='Libre accès'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
