# Generated by Django 5.1.3 on 2025-02-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_order_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalproduct',
            name='internal_id',
            field=models.PositiveBigIntegerField(),
        ),
    ]
