# Generated by Django 5.1.3 on 2025-02-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_internalproduct_internal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalproduct',
            name='universe',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Univers'),
        ),
    ]
