# Generated by Django 5.1.3 on 2024-12-09 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_pharmacy_id_nat_alter_globalproduct_free_access_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalproduct',
            old_name='product_name',
            new_name='name',
        ),
    ]
