# Generated by Django 5.1.3 on 2024-12-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_rename_product_name_globalproduct_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='sent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
