# Generated by Django 5.1.3 on 2024-12-11 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_order_delivery_date_alter_order_sent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='pharmacy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.pharmacy'),
            preserve_default=False,
        ),
    ]
