# Generated by Django 5.1.3 on 2024-12-12 02:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_supplier_pharmacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorysnapshot',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
