# Generated by Django 5.1.3 on 2024-12-12 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_inventorysnapshot_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorysnapshot',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AddConstraint(
            model_name='inventorysnapshot',
            constraint=models.UniqueConstraint(fields=('product', 'date'), name='unique_snapshot_constraint'),
        ),
    ]
