# Generated by Django 5.1.3 on 2024-12-12 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_alter_inventorysnapshot_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorysnapshot',
            name='date',
            field=models.DateField(),
        ),
    ]
