# Generated by Django 5.1.3 on 2024-12-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_alter_inventorysnapshot_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='internalproduct',
            name='unique_product_constraint',
        ),
        migrations.AddConstraint(
            model_name='internalproduct',
            constraint=models.UniqueConstraint(fields=('pharmacy', 'internal_id'), name='unique_product_constraint'),
        ),
    ]
