# Generated by Django 5.1.3 on 2024-12-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_remove_internalproduct_unique_product_constraint_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='supplier',
            name='unique_supplier_constraint',
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('pharmacy', 'code_supplier'), name='unique_supplier_constraint'),
        ),
    ]
