# Generated by Django 5.1.3 on 2024-12-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_remove_supplier_unique_supplier_constraint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalproduct',
            name='internal_id',
            field=models.BigIntegerField(),
        ),
    ]
